""""""""""
" Vundle "
""""""""""
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'jiangmiao/auto-pairs'
Plugin 'python-mode/python-mode'
Plugin 'altercation/vim-colors-solarized'
Plugin 'airblade/vim-gitgutter'
Plugin 'ycm-core/YouCompleteMe'
Plugin 'psf/black'
Plugin 'Yggdroot/indentLine'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" END Vundle

""""""""""""""
" Workarounds "
""""""""""""""
" auto-pairs breaks some accent characters
" see: https://github.com/jiangmiao/auto-pairs/issues/88
let g:AutoPairsShortcutBackInsert=''
let g:AutoPairsShortcutJump=''
let g:AutoPairsMoveCharacter=''

""""""""""""""""""""
" General settings "
""""""""""""""""""""
syntax on			" Highlight syntax

" Hide line numbers when file has no filetype or no file was opened
autocmd BufNewFile,BufRead,VimEnter * if &ft == '' | set nonumber | endif
set number			" show line numbers

				" toggle line numbering
nnoremap <F3> :set nonumber! colorcolumn=<CR> \| :GitGutterBufferToggle<CR> \| :IndentLinesToggle<CR>
imap <F3> <C-O><F3>

" set cursorcolumn		" highlight the cursor's column
" set cursorline			" highlight the line under the cursor
nnoremap <F7> :set nocursorcolumn! nocursorline!<CR>
imap <F7> <C-O><F7>
set showmatch			" shows matching part of bracket pairs (), [], {}

set enc=utf-8			" utf-8 by default

set pastetoggle=<F2>		" Toggle auto-indenting for code paste

set modeline			" Enable modelines
set modelines=5

set scrolloff=10		" let 10 lines before/after cursor during scroll

set exrc			" enable usage of additional .vimrc files from working directory
set secure			" prohibit .vimrc files to execute shell, create files, etc...

if has("mac")
	set backspace=2
endif

let g:vim_virtualenv = '~/.virtualenvs/vim'

"""""""""""""""
" Color theme "
"""""""""""""""
set t_Co=256			" Use 256 colours (Use this setting only if your terminal supports 256 colours)

" Solarized colorscheme
let g:solarized_termtrans=1 	" 1|0 background transparent
colorscheme solarized
set background=dark

""""""""""""""""""""
" Buffers settings "
""""""""""""""""""""
set switchbuf=useopen
nmap <F9> :bprev<CR>
nmap <F10> :bnext<CR>

"""""""""""""
" Powerline "
"""""""""""""
function StartPowerline()
  python3 from powerline.vim import setup as powerline_setup
  python3 powerline_setup()
  python3 del powerline_setup
endfunction

function GetPythonVersion()
  let g:python_version = substitute(system(g:vim_virtualenv . "/bin/python3 -V"), '^python \([0-9]\+\.[0-9]\+\)\(\.[0-9]\+\)\?.*\c', '\1', '')
endfunction

call GetPythonVersion()
let python_arch_path = '/usr/lib/python' . g:python_version . '/site-packages/'
let python_homebrew_path = '/usr/local/lib/python' . g:python_version . '/site-packages/'

if isdirectory(python_arch_path)
  " Arch Linux
  python3 import vim
  python3 sys.path.append(vim.eval("python_arch_path"))
  call StartPowerline()
elseif isdirectory('/usr/lib/python3/dist-packages/')
  " Debian based Linux
  python3 sys.path.append('/usr/lib/python3/dist-packages/')
  call StartPowerline()
elseif isdirectory(python_homebrew_path)
  " OSX / homebrew
  python3 import vim
  python3 sys.path.append(vim.eval("python_homebrew_path"))
  call StartPowerline()
endif

" Always show statusline
set laststatus=2

"""""""""""""""""""
" Search settings "
"""""""""""""""""""
set incsearch			" Incremental search
set hlsearch			" Highlight search
set ignorecase			" Case insensitive search
set smartcase			" Search for capital letters specifically

" Press F4 to toggle highlighting on/off, and show current value.
noremap <F4> :set hlsearch! hlsearch?<CR>
" Press F5 to clear highlighted search
noremap <F5> :nohlsearch<CR>

" Press Return to temporarily get out of the highlighted search.
nnoremap <CR> :nohlsearch<CR><CR>

" Pressing F8 will highlight all occurrences of the current word.
nnoremap <F8> :let @/='\<<C-R>=expand("<cword>")<CR>\>'<CR>:set hls<CR>

""""""""""""""""
" Code folding "
""""""""""""""""
" Enable folding
set foldmethod=indent
set foldlevel=99

" Enable folding with the spacebar
nnoremap <space> za
vnoremap <space> zf

"""""""""
" Black "
"""""""""
let g:black_virtualenv = g:vim_virtualenv

" autocmd BufWritePre *.py execute ':Black'
"
nnoremap <F11> :Black<CR>

"""""""""""""""
" Python mode "
"""""""""""""""
" Use python3 syntax checking
let g:pymode_python = 'python3'

" Python 120 characters line length
let g:pymode_options_max_line_length=120
autocmd FileType python set colorcolumn=120

" Highlight trailing spaces
highlight BadWhitespace ctermfg=16 ctermbg=166 guifg=#000000 guibg=#d75f00
autocmd FileType python match BadWhitespace /\s\+$/

" If you prefer the Omni-Completion tip window to close when a selection is
" made, these lines close it on movement in insert mode or when leaving
" insert mode
autocmd CursorMovedI * if pumvisible() == 0|pclose|endif
autocmd InsertLeave * if pumvisible() == 0|pclose|endif

" Disable docstring preview on auto-completion for Python
autocmd FileType python set completeopt=menuone,noinsert

" Enable Rope support
let g:pymode_rope = 1
" let g:pymode_rope_completion = 1
" let g:pymode_rope_complete_on_dot = 1
" let g:pymode_rope_completion_bind = '<C-Space>'

"""""""""""""""""
" CSS, HTML, JS "
"""""""""""""""""
" Use 2 spaces
autocmd FileType css,html,javascript set ts=2 sts=2 sw=2 expandtab

""""""""
" YAML "
""""""""
" Use 2 spaces YAML
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab

"""""""""""""""""""""""""""""
" Highlight repeating lines "
"""""""""""""""""""""""""""""
function! HighlightRepeats() range
  let lineCounts = {}
  let lineNum = a:firstline
  while lineNum <= a:lastline
    let lineText = getline(lineNum)
    if lineText != ""
      let lineCounts[lineText] = (has_key(lineCounts, lineText) ? lineCounts[lineText] : 0) + 1
    endif
    let lineNum = lineNum + 1
  endwhile
  exe 'syn clear Repeat'
  for lineText in keys(lineCounts)
    if lineCounts[lineText] >= 2
      exe 'syn match Repeat "^' . escape(lineText, '".\^$*[]') . '$"'
    endif
  endfor
endfunction

command! -range=% HighlightRepeats <line1>,<line2>call HighlightRepeats()
map <F6> :HighlightRepeats<CR>

"""""""""""""""""""
" Slides commands "
"""""""""""""""""""

command! Tl normal a <!-- .element class="text-left" -->

""""""""""""""
" IndentLine "
""""""""""""""
let g:indentLine_char_list = ['|', '¦', '┆', '┊']
"let g:vim_json_conceal=0
"let g:markdown_syntax_conceal=0
