# Inserts a blank line between shell prompts
add_newline = true

[aws]
disabled = true

[azure]
disabled = true

[directory]
truncate_to_repo = false
style = "bold blue"
repo_root_style = "bold cyan"

[gcloud]
disabled = true

[git_branch]
style = "bold green"

[status]
disabled = false
format = '[$symbol ]($style) '

[time]
disabled = false
utc_time_offset = "local"
format = "[$time]($style) "
time_format = "%T"
