#!/bin/bash
BATTERY="${1:-0}"

ACPI="$(acpi -b | grep "Battery $BATTERY")"
if [[ -z "$ACPI" ]]; then
	exit
fi
read -r STATUS PERCENT TIME <<< "$(echo "$ACPI" | sed -r "s/^Battery 0: (Full|(Dis)?[Cc]harging), ([0-9]+)%(, ([0-9]+:[0-9]+:[0-9]+))?.*/\1 \3 \5/")"

TEXT=""
SHORT=""
COLOR=""

if [[ "$STATUS" == "Discharging" ]]; then
	if [[ $PERCENT -le 100 && $PERCENT -gt 80 ]]; then
		SHORT="\xef\x89\x80\x20"
	elif [[ $PERCENT -le 80 && $PERCENT -gt 60 ]]; then
		SHORT="\xef\x89\x81\x20"
	elif [[ $PERCENT -le 60 && $PERCENT -gt 40 ]]; then
		SHORT="\xef\x89\x82\x20"
	elif [[ $PERCENT -le 40 && $PERCENT -gt 20 ]]; then
		SHORT="\xef\x89\x83\x20"
		COLOR="#b58900"
	elif [[ $PERCENT -le 20 && $PERCENT -gt 0 ]]; then
		SHORT="\xef\x89\x84\x20"
		COLOR="#dc322f"
	fi
elif [[ "$STATUS" == "Charging" ]]; then
	SHORT="\xef\x87\xa6\x20"
elif [[ "$STATUS" == "Full" ]]; then
	SHORT="\xef\x89\x80\x20"
else
	exit
fi
SHORT+=" ${PERCENT}%"
TEXT="$SHORT"
if [[ ! -z "$TIME" ]]; then
	TEXT+=" ($TIME)"
fi
echo -e "$TEXT"
echo -e "$SHORT"
echo "$COLOR"
