#!/bin/sh
dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Stop
killall -SIGUSR1 dunst
i3lock -d -I 30 --no-unlock-indicator --tiling --image="$1" --nofork
killall -SIGUSR2 dunst
