#!/bin/bash
revert() {
	now="$(date "+%H%M")"
	if [[ "${now#0}" -ge 800 ]] && [[ "${now#0}" -lt 1900 ]]; then
		xset dpms 300 300 300
	else
		xset dpms 60 60 60
	fi
}

# If Spotify is running, stop playback
sp_dest="org.mpris.MediaPlayer2.spotify"
sp_path="/org/mpris/MediaPlayer2"
sp_memb="org.mpris.MediaPlayer2.Player"
if dbus-send --print-reply --dest=org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus.ListNames | grep -q "$sp_dest"; then
	dbus-send --type=method_call --dest="$sp_dest" "$sp_path" "$sp_memb".Stop
fi

dunstctl set-paused true
trap revert HUP INT TERM
xset +dpms dpms 30 30 30 
WALLPAPER=$(~/.config/i3/scripts/lockscreen_wallpaper "$1")
if [ -z "$WALLPAPER" ]; then
	i3lock --no-unlock-indicator --nofork
else
	i3lock --no-unlock-indicator --tiling --image="$WALLPAPER" --nofork
fi
revert
dunstctl set-paused false
