#!/bin/bash

sp_dest="org.mpris.MediaPlayer2.spotify"
sp_path="/org/mpris/MediaPlayer2"
sp_memb="org.mpris.MediaPlayer2.Player"
prop_get="org.freedesktop.DBus.Properties.Get"

if [[ ${BLOCK_BUTTON:-0} == 1 ]]; then
	dbus-send --print-reply --dest="$sp_dest" "$sp_path" "$sp_memb".PlayPause > /dev/null
fi

if ! dbus-send --print-reply --dest=org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus.ListNames | grep -q "$sp_dest"; then
	exit
fi

SPOTIFY_METADATA="$(dbus-send                                                \
 --print-reply                                  `# We need the reply.`       \
 --dest="$sp_dest"                                                           \
 "$sp_path"                                                                  \
 "$prop_get"                                                                 \
 string:"$sp_memb" string:'Metadata'                                         \
 | grep -Ev "^method"                           `# Ignore the first line.`   \
 | grep -Eo '("(.*)")|(\b[0-9][a-zA-Z0-9.]*\b)' `# Filter interesting fiels.`\
 | sed -E '2~2 a|'                              `# Mark odd fields.`         \
 | tr -d '\n'                                   `# Remove all newlines.`     \
 | sed -E 's/\|/\n/g'                           `# Restore newlines.`        \
 | sed -E 's/(xesam:)|(mpris:)//'               `# Remove ns prefixes.`      \
 | sed -E 's/^"//'                              `# Strip leading...`         \
 | sed -E 's/"$//'                              `# ...and trailing quotes.`  \
 | sed -E 's/\"+/|/'                            `# Regard "" as seperator.`  \
 | sed -E 's/ +/ /g'                            `# Merge consecutive spaces.`\
)"

TrackArtist=$(echo "$SPOTIFY_METADATA" | sed -n 's/artist|//p')
TrackTitle=$(echo "$SPOTIFY_METADATA" | sed -n 's/title|//p')

if dbus-send --print-reply --dest="$sp_dest" "$sp_path" "$prop_get" string:"$sp_memb" string:'PlaybackStatus' | grep -q Playing; then
	PlaybackStatus=""
	Color="#2EBD59"
else
	PlaybackStatus=""
	Color="#676E7D"
fi


echo "$TrackTitle - $TrackArtist $PlaybackStatus"
echo "$PlaybackStatus"
echo "$Color"
