#!/bin/bash
sink="$(pactl get-default-sink)"

if [ -z "$1" ]; then
	if [[ ${BLOCK_BUTTON:-0} == 1 ]]; then
		$0 mute
	fi
	mute=$(pactl get-sink-mute "$sink" | sed -n -E 's/Mute:\s([yes|no])/\1/p')
	if [[ $mute == yes ]]; then
		echo " Mute"
	else
		echo " $(pactl get-sink-volume "$sink" | sed -n -E 's@^Volume:\s[^/]+/\s*([0-9]+%)\s+.*@\1@p')"
	fi
else
	case "$1" in
		"up")
			pactl set-sink-volume "$sink" +1%
			;;
		"down")
			pactl set-sink-volume "$sink" -1%
			;;
		"mute")
			pactl set-sink-mute "$sink" toggle
			;;
	esac
fi
