#!/bin/bash
files=(~/Pictures/Wallpapers/*)

WALLPAPERS=()
SCREENS_COUNT=$(xrandr | grep -c  " connected ")
for ((i=0; i<SCREENS_COUNT; i++)); do
	WALLPAPERS+=( "--bg-fill" "$(printf "%s\n" "${files[RANDOM % ${#files[@]}]}")" )
done

feh -B black "${WALLPAPERS[@]}"
