#!/bin/bash
WALLPAPERS_DIR="$HOME/Pictures/Wallpapers"
[ ! -d "$WALLPAPERS_DIR" ] && exit

files=("$WALLPAPERS_DIR"/*)

DisplayName()
{
  local ttynr="$1"
  declare -A property
  for session in $(loginctl --no-legend list-sessions | awk '{ print $1 }' ); do
    while IFS="=" read -r key value ; do
      property[$key]="$value"
    done < <(loginctl show-session "$session")

    if [ "${property[VTNr]}" = "$ttynr" ] && [ -n "${property[Display]}" ]; then
      echo "${property[Display]}"
      return 0
    fi
  done
  return 1
}

DISPLAY="$(/usr/bin/w -h "$USER" | awk '/\s:[0-9.]+/{print $2}')"
if [ -z "$DISPLAY" ]; then
	DISPLAY="$(DisplayName 7)"
	if [ -z "$DISPLAY" ]; then
		echo "No display found, exiting"
		exit 1
	fi
fi
export DISPLAY

WALLPAPERS=()
SCREENS_COUNT=$(xrandr | grep -c  " connected ")
for ((i=0; i<SCREENS_COUNT; i++)); do
	WALLPAPERS+=( "--bg-fill" "$(printf "%s\n" "${files[RANDOM % ${#files[@]}]}")" )
done

feh -B black "${WALLPAPERS[@]}"
